controllers/ResultController.php
<?php

namespace app\controllers;

use Yii;
use app\models\UserTopic;
use app\models\UserTopicSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ResultController implements the CRUD actions for UserTopic model.
 */
class ResultController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserTopic models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest || !in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $searchModel = new UserTopicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->pagination->pageSize=255;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionExport()
    {
        if(!in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $ut = UserTopic::find()->all();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        header('Content-Type: application/csv');
        header('Content-Disposition: attachment; filename=si-'.date('Y-m-d_H-i-s').'.csv');
        header("Pragma: no-cache");
        $outF = fopen('php://temp', 'r+');
        $header = null;
        foreach($ut as $topic) {
            $data = [
                'id' => $topic->id,
                'user_id' => $topic->user->id,
                'e-mail' => $topic->userEmail,
                'ФИО' => $topic->userName,
                'Дата рождения' => $topic->userBirtdate,
                'topic_id' => $topic->topic_id,
                'Тема' => $topic->topicName,
                'Дата темы' => $topic->topic->show_date,
                'Результат' => $topic->topicResult,
                'Начато' => $topic->create_date,
                'Закончено' => $topic->end_date,
            ];
            if (!$header) {
                foreach ( $data as $h => $v ) {
                    $header[] = $h;
                }
                fputcsv($outF, $header, ';', '"');
            }
            fputcsv($outF, $data, ';', '"');
        }
        rewind($outF);
        $res = '';
        while($str = fgets($outF)) {
            $res .= $str;
        }
        fclose ($outF);
        return $res;
    }

    /**
     * Finds the UserTopic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserTopic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserTopic::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/result/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserTopic */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-topic-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'topic_id')->textInput() ?>

    <?= $form->field($model, 'end_date')->textInput() ?>

    <?= $form->field($model, 'create_date')->textInput() ?>

    <?= $form->field($model, 'modify_date')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/result/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserTopicSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-topic-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'topic_id') ?>

    <?= $form->field($model, 'end_date') ?>

    <?= $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'modify_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/result/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserTopicSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Результаты';
$this->params['breadcrumbs'][] = $this->title;
?>
<?=Html::a("Экспорт", "/result/export", ['target' => '_blank'])?>
<div class="user-topic-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'user_id',
            'userEmail',
            'userName',
            //'topic_id',
            'topicName',
            'topicResult',
            'create_date',
            'end_date',
            // 'modify_date',
        ],
    ]); ?>

</div>