controllers/SearchController.php
<?php

namespace app\controllers;

use app\models\Question;
use Yii;
use app\models\UserAnswer;
use app\models\UserAnswerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\HttpException;

/**
 * SearchController implements the CRUD actions for UserAnswer model.
 */
class SearchController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserAnswer models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest || !in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $searchModel = new UserAnswerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->pagination->pageSize=1000;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCorrect($id)
    {
        if(!in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $ua = UserAnswer::findOne($id);
        $ua->is_correct = 1;
        $ua->save();
        $this->redirect(Yii::$app->request->referrer);
    }

    public function actionWrong($id)
    {
        if(!in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $ua = UserAnswer::findOne($id);
        $ua->is_correct = 0;
        $ua->save();

        $this->redirect(Yii::$app->request->referrer);
    }

    private static function printTristate($val, $vals)
    {
        if ( null === $val ) return $vals[0];
        else return $val ? $vals[2] : $vals[1];
    }
    private static function answerTime($d1, $d2) {
        $datetime1 = date_create($d1);
        $datetime2 = date_create($d2);
        $interval = date_diff($datetime1, $datetime2);
        return $interval->format("%s");
    }

    public function actionExport()
    {
        if(!in_array ( Yii::$app->user->getIdentity()->email, Yii::$app->params['adminEmails'])) {
            throw new HttpException(401);
        }
        $ua = UserAnswer::find()->all();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
        header('Content-Type: application/csv');
        header('Content-Disposition: attachment; filename=si-'.date('Y-m-d_H-i-s').'.csv');
        header("Pragma: no-cache");
        $outF = fopen('php://temp', 'r+');
        $header = null;
        foreach($ua as $answer) {
            $data = [
                'id' => $answer->id,
                'user_id' => $answer->user->id,
                'e-mail' => $answer->user->email,
                'ФИО' => $answer->user->name,
                'Дата рождения' => $answer->userBirtdate,
                'topic_id' => $answer->question->topic->id,
                'Тема' => $answer->question->topic->name,
                'Дата темы' => $answer->question->topic->show_date,
                'q_id' => $answer->question->id,
                'Цена вопроса' => $answer->question->value,
                'Текст вопроса' => $answer->question->text,
                'Ответ' => $answer->text,
                'Правильный ответ' => $answer->question->right,
                'Пропущен' => $this->printTristate($answer->skipped, ['-', 'Нет', 'Да']),
                'Правильный' => $this->printTristate($answer->is_correct, ['-', 'Нет', 'Да']),
                'Время ответа' => $this->answerTime($answer->create_date, $answer->answer_date),
            ];
            if (!$header) {
                foreach ( $data as $h => $v ) {
                    $header[] = $h;
                }
                fputcsv($outF, $header, ';', '"');
            }
            fputcsv($outF, $data, ';', '"');
        }
        rewind($outF);
        $res = '';
        while($str = fgets($outF)) {
            $res .= $str;
        }
        fclose ($outF);
        return $res;
    }

    /**
     * Finds the UserAnswer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserAnswer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
/*    protected function findModel($id)
    {
        if (($model = UserAnswer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
*/
}

views/search/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserAnswer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-answer-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'question_id')->textInput() ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'skipped')->textInput() ?>

    <?= $form->field($model, 'is_correct')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/search/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserAnswerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-answer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'question_id') ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'skipped') ?>

    <?php // echo $form->field($model, 'is_correct') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'modify_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/search/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserAnswerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ответы';
$this->params['breadcrumbs'][] = $this->title;
?>
<?=Html::a("Экспорт", "/search/export", ['target' => '_blank'])?>
<div class="user-answer-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <!--p>
        <?= Html::a('Create User Answer', ['create'], ['class' => 'btn btn-success']) ?>
    </p-->

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            'userEmail',
            'userName',
            //'topicName',
            //'questionText',
            [
                'attribute' =>'questionValue',
                'headerOptions' => ['width' => '60px'],
            ],
            'questionRight',
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'correct' => function($url,$model){
                        if($model->skipped || 1 === $model->is_correct) return '';
                        return Html::a("<span class='glyphicon glyphicon-plus-sign' style='color:green;'></span>", $url);
                    },
                ],
                'template' => '{correct}',
            ],
            'text',
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'wrong' => function($url,$model){
                        if($model->skipped || 0 === $model->is_correct) return '';
                        return Html::a("<span class='glyphicon glyphicon-minus-sign' style='color:red;'></span>", $url);
                    },
                ],
                'template' => '{wrong}',
            ],
            //'skipped',
            [
                'attribute' =>'is_correct',
                'headerOptions' => ['width' => '10px'],
            ],
            [
                'attribute' => '?',
                'label' => 'Время ответа',
                'format' => 'integer',
                'content' => function($m) {
                    $datetime1 = date_create($m->create_date);
                    $datetime2 = date_create($m->answer_date);
                    $interval = date_diff($datetime1, $datetime2);
                    $val = $interval->format("%s");
                    if($val > 20) {
                        return '<span style="color:red;font-weight: bold;">'.$val.'</span>';
                    } else {
                        return '<span style="color:green;font-weight: bold;">'.$val.'</span>';
                    }
                }
            ],
            'create_date',
            //'modify_date',
        ],
    ]); ?>

</div>